In [1]:
import pandas as pd
import os
from datetime import datetime

In [2]:
# 1. Create a DataFrame for the 201908-citibike-tripdata data. 
# citibike_dataset = os.path.join('C:Users>jwill>Desktop>AnalysisProjects>Module 15 Challenge>201908-citibike-tripdata.csv')
citibike_df = pd.read_csv("./Resources/201908-citibike-tripdata.csv")
citibike_df.sample(10)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
624562,573,50:27.4,00:01.4,359.0,E 47 St & Park Ave,40.755103,-73.974987,2006.0,Central Park S & 6 Ave,40.765909,-73.976342,35116,Subscriber,1979,1
774832,898,43:59.8,58:58.4,426.0,West St & Chambers St,40.717548,-74.013221,434.0,9 Ave & W 18 St,40.743174,-74.003664,28719,Customer,1969,0
21629,667,53:41.6,04:49.0,416.0,Cumberland St & Lafayette Ave,40.687534,-73.972652,258.0,DeKalb Ave & Vanderbilt Ave,40.689407,-73.968855,32601,Subscriber,1973,2
268523,1048,00:20.3,17:49.2,164.0,E 47 St & 2 Ave,40.753231,-73.970325,509.0,9 Ave & W 22 St,40.745497,-74.001971,18337,Subscriber,1982,1
779076,412,21:49.1,28:41.4,505.0,6 Ave & W 33 St,40.749013,-73.988484,484.0,W 44 St & 5 Ave,40.755003,-73.980144,15670,Subscriber,1975,1
243721,239,58:54.8,02:53.9,362.0,Broadway & W 37 St,40.751726,-73.987535,526.0,E 33 St & 5 Ave,40.747659,-73.984907,21876,Subscriber,1986,1
961144,1140,29:46.1,48:46.2,408.0,Market St & Cherry St,40.710762,-73.994004,539.0,Metropolitan Ave & Bedford Ave,40.715348,-73.960241,25790,Subscriber,1984,1
785172,1055,34:51.8,52:27.5,474.0,5 Ave & E 29 St,40.745168,-73.986831,341.0,Stanton St & Mangin St,40.717821,-73.976289,27959,Subscriber,1989,1
864342,907,19:11.4,34:18.8,523.0,W 38 St & 8 Ave,40.754666,-73.991382,368.0,Carmine St & 6 Ave,40.730386,-74.002150,17699,Subscriber,1961,1
280756,872,13:19.5,27:51.8,285.0,Broadway & E 14 St,40.734546,-73.990741,3260.0,Mercer St & Bleecker St,40.727064,-73.996621,24802,Subscriber,1969,0

In [3]:
# 2. Check the datatypes of your columns. 
citibike_df.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id           float64
start station name          object
start station latitude     float64
start station longitude    float64
end station id             float64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
usertype                    object
birth year                   int64
gender                       int64
dtype: object

In [4]:
# 3. Convert the 'tripduration' column to datetime datatype.
citibike_df['tripduration'] = pd.to_datetime(citibike_df['tripduration'], unit='s')

In [5]:
# 4. Check the datatypes of your columns. 
citibike_df.dtypes

tripduration               datetime64[ns]
starttime                          object
stoptime                           object
start station id                  float64
start station name                 object
start station latitude            float64
start station longitude           float64
end station id                    float64
end station name                   object
end station latitude              float64
end station longitude             float64
bikeid                              int64
usertype                           object
birth year                          int64
gender                              int64
dtype: object

In [9]:
# View sample of the updated DF
citibike_df.sample(10)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
38636,1970-01-01 00:21:02,52:05.1,13:07.7,415.0,Pearl St & Hanover Square,40.704718,-74.009260,426.0,West St & Chambers St,40.717548,-74.013221,32258,Subscriber,1984,1
658892,1970-01-01 00:13:11,36:46.8,49:58.5,351.0,Front St & Maiden Ln,40.705310,-74.006126,312.0,Allen St & Stanton St,40.722055,-73.989111,18729,Subscriber,1994,1
111619,1970-01-01 00:12:30,01:07.2,13:37.7,259.0,South St & Whitehall St,40.701221,-74.012342,332.0,Cherry St,40.712199,-73.979481,25265,Subscriber,1977,1
647678,1970-01-01 00:22:49,17:25.1,40:14.4,161.0,LaGuardia Pl & W 3 St,40.729170,-73.998102,3472.0,W 15 St & 10 Ave,40.742754,-74.007474,29883,Customer,1969,0
377906,1970-01-01 00:21:00,50:16.7,11:17.6,462.0,W 22 St & 10 Ave,40.746920,-74.004519,361.0,Allen St & Hester St,40.716059,-73.991908,28976,Subscriber,1992,1
173937,1970-01-01 00:38:00,54:49.0,32:49.7,217.0,Old Fulton St,40.702772,-73.993836,387.0,Centre St & Chambers St,40.712733,-74.004607,34073,Subscriber,1987,1
803762,1970-01-01 00:07:14,08:16.7,15:31.2,3602.0,31 Ave & 34 St,40.763154,-73.920827,3566.0,Crescent St & 35 Ave,40.759628,-73.932146,16360,Subscriber,1988,1
898287,1970-01-01 00:08:35,37:40.8,46:16.3,342.0,Columbia St & Rivington St,40.717400,-73.980166,531.0,Forsyth St & Broome St,40.718939,-73.992663,38642,Subscriber,1946,1
294290,1970-01-01 00:32:34,37:02.7,09:37.2,405.0,Washington St & Gansevoort St,40.739323,-74.008119,3172.0,W 74 St & Columbus Ave,40.778567,-73.977550,35251,Subscriber,1967,1
86629,1970-01-01 00:22:01,18:44.0,40:45.6,3110.0,Meserole Ave & Manhattan Ave,40.727086,-73.952991,3116.0,Huron St & Franklin St,40.732660,-73.958260,19427,Subscriber,1995,1

In [8]:
# 5. Export the Dataframe as a new CSV file without the index.
output_data_filename = "NYC_CityBike_data_cleaned.csv"
citibike_df.to_csv(output_data_filename, index=False)